erikabusiness/koru-mobile-projeto-3

- classes/pessoa.dart
- main.dart
Criar atributo data de nascimento e idade.
- Foi criado o atributo dataDeNascimento e idade.
- Sem dependências.
> Jhonny/feature/pessoa atribuição data de nascimento idade.

- classes/pessoa.dart
- main.dart
Criar o método calcularIdade (retorno: int)
- O método deve calcular a idade da pessoa com base na data atual e na sua data de nascimento.
- O cálculo deve utilizar a data atual de maneira dinâmica. Isso significa que o método deverá funcionar em hoje ou daqui a 10 anos, sem precisar ser alterado. Portanto, você não poderá partir do princípio que o ano sempre será 2024.
- Esse método deverá ser chamado logo que objetos do tipo Pessoa forem criados, atualizando então, o atributo idade que foi declarado no início da classe. Para isso, você deverá chamar esse método no construtor da classe, atribuindo o seu retorno ao atributo idade.
- Foi criado o método calcularIdade utilizando _DateTime_ e seu método _difference_ para verificar a diferença, em anos, entre duas datas.
- O retorno do método …
> feat: adiciona o método calcular idade na classe pessoa 

- classes/pessoa.dart
- main.dart
Criar método VerificarMaioridade();
- Foi criado o método `verificarMaioridade()`.
- O resultado da operação de verificação foi atribuída a `String verificar` . 
- Sem dependências.
> Criar método para calcular maioridade

- classes/pessoa.dart
- main.dart
Criar método falar
- falar (retorno: void):
-Parâmetros:
- fala (tipo: String): representa o que a pessoa está falando.
- O método deve receber um parâmetro do tipo String, que representa a fala da pessoa, e realizar um print dessa fala.
- Exemplo: “Maria diz: Oi, tudo bem?”.
- Foi criada a função de retorno vazio na Classe Pessoa, com parâmetro do tipo String falar.
- Foi impresso a frase com o valor recebido do atributo nome e o parâmetro recebido, "Maria diz: Oi, tudo bem?”.
- Foi chamado o método no arquivo main.
> feat: Método falar - Classe Pessoa

- classes/produto.dart
Criar Atributo: qtdEmEstoque (tipo: int)
- Representa a quantidade do produto em estoque (exemplo: 5).
- Atributo obrigatório, cujo valor inicial deve ser recebido no construtor da classe.
☑️ Adicionei o atributo qtdEmEstoque na classe Produto.
> feat: adição do atributo qtdEmEstoque e qtdVendida na classe Produto

- classes/produto.dart
- main.dart
Criar método: realizarVenda na classe Produto e chamar o método na main.
☑️ adicionar atributos e método realizarVenda para classe Produto.
☑️ chamar método na main.
> Feature: - criar método realizarVenda

- classes/produto.dart
- main.dart
- Criar o atributo nome;
- Criar o atributo valor;
- Criar o método verReceitaGerada;
- Criação dos atributos nome e valor;
- Criação do método verReceitaGerada;
- Adição dos atributos obrigatórios no construtor da classe Produto;
- Adição dos testes dos métodos da classe Produto na classe Main;
- Sem dependências.
> feature: adicionados os atributos e metodo restantes da classe Produto

- classes/revendedor.dart
- Criar atributo produtosVendidos;
- Criado o atributo produtosVendidos do tipo array de Produtos na classe Revendedor, inicializado vazio e não é recebido no construtor da classe.
> feat: adiciona o atributo produtosVendidos na classe Revendedor

- classes/enums.dart
- classes/pessoa.dart
- main.dart
-  Criar um Enum chamado Gênero, contendo os seguintes gêneros:
- Feminino, Masculino e Outro.
-  Atualizar classe Pessoa com o novo atributo Genero
- Representa o gênero da pessoa (exemplo: Genero.feminino).
-  Atributo imutável e obrigatório, que deve ser recebido no construtor da classe.
- Criei o Enum contendo gêneros para pessoa.
- Criei um atributo imutável que foi recebido no método construtor da classe.
> feat: enum contendo gêneros para pessoa e atributo imutável de gênero

- classes/enums.dart
- classes/pessoa.dart
- classes/revendedor.dart
- main.dart
falar (sobrescrever):
- O método continua recebendo o parâmetro do tipo String, que representa a fala da pessoa.
- Deve-se realizar um print da fala, mas especificando que é um revendedor que está falando.
- Deve-se utilizar um switch/case observando o gênero do revendedor, para que a saída seja personalizada de acordo com isso.
- Exemplos:
- Gênero masculino: “Revendedor João diz: Temos promoções”.
- Gênero feminino: “Revendedora Maria diz: Temos promoções”.
- Gênero neutro: “Pessoa revendedora Cris diz: Temos promoções”.
- Reescrevido o método falar com override, na classe revendedor.
- No método, há um switch case, no qual é impresso a fala do revendedor de acordo com seu gênero.
- Feito teste do método na main.
> feat: Método falar da classe Revendedor

- classes/cliente.dart
- main.dart
- Criar o método `comprarProduto (retorno: void) `na classe Cliente, responsável por realizar uma compra de um produto com um revendedor.
- Deve receber os parâmetros: 
- produto (tipo: Produto): representa o produto que o cliente está comprando.
- revendedor (tipo: Revendedor): representa o revendedor com o qual o cliente está comprando aquele produto.
- O método deve receber um parâmetro do tipo Produto e um do tipo Revendedor e verificar se aquele cliente possui dinheiro suficiente para comprar aquele produto, de acordo com o seu valor:
- Caso possua:
Chamar o método venderProduto daquele revendedor;
Diminuir o valor do produto do valor do dinheiro do cliente;
Adicionar o produto na array de produtos comprados por aquele cliente.
- Caso não possua:
Realizar um print dizendo que a …
> Método comprarProduto na classe Cliente 

- classes/revendedor.dart
Criar método venderProduto 
- Método responsável por realizar uma venda de um produto.
- foi criado o método usando um método já criado chamado realizarVendar e em seguida foi criado a lógica para vender o
produto.
> feat:  adicionando método venderProduto

- classes/pessoa.dart
- classes/produto.dart
- main.dart
- utils.dart
- Implementar as oportunidades de melhoria indicadas pela tutora.
- O método calcularIdade foi alterado para privado;
- O atributo idade foi alterado para privado;
- Foi excluído as chaves do construtor da classe Produto, pois quando o construtor não vai realizar nenhuma ação (chamar alguma função, por exemplo), não é necessário abrir e fechar chaves;
- Foi criado um método chamado `fixarDuasCasasDecimais` para fixar a quantidade de números depois da casa decimal em 2. O método foi criado em `utils.dart` para abstrair a lógica de arredondar os valores e poder ser reutilizado quando for necessário em outros momentos.
> Implementar oportunidades de melhoria - atividade 1

- classes/cliente.dart
Adicionar o atributo de produtos comprados pelo cliente
- Foi adicionado a variável de produtos comprados (List<Produto> produtosComprados) na classe Cliente
-
> - feat: criação do atributo produtosComprados dentro da classe Cliente

- classes/revendedor.dart
- main.dart
-  Criar atributo matrícula revendedor;
- Representa a matrícula da pessoa revendedora (exemplo: “12345”).
- Atributo imutável e obrigatório, que deve ser recebido no construtor da classe.
- Criado o atributo matrícula revendedor conforme os detalhes da tarefa.
- Criado uma instância da classe revendedor para testar o atributo matrícula.
> feat: adição do atributo matrícula na classe revendedor.

- classes/cliente.dart
Adicionar o atributo dinheiro
- Foi atribuído a classe Cliente, o atributo Dinheiro, para que retorne quanto de dinheiro o cliente possui.
-
> Feat: Cliente - Dinheiro

- main.dart
Adicionar o método AdicionarDinheiro.
- Foi atribuído o método para adição de dinheiro, retornando quanto foi adicionado a carteira.
- Foi utilizado o atributo Dinheiro, para que houvesse a soma do que já tinha, com o que foi adicionado.
- Além das somas, foi passado um parâmetro 'null', para construção da classe.
-
> Feat: Cliente - adicionar dinheiro

- classes/cliente.dart
- main.dart
- readme.md
Atualizar documentação
- A documentação foi atualizada com informações das novas classes e alterações pontuais nas existentes.
- Removi imports duplicados e não usados
> docs: atualizar documentação

- classes/cliente.dart
- Criar método verResumo que utiliza as funções criadas anteriormente e realiza um print do resumo de total gasto e média aritmética.
- Criação do Método verResumo na classe Cliente;
- Teste de impressão com recebimento dos parâmetros na classe main do repositório local;
- Utilização da função fixarDuasCasasDecimais na impressão dos valores;
> feat: criar método verResumo na classe Cliente

- classes/produto.dart
- classes/revendedor.dart
- main.dart
- atualizar método venderProduto para lançar throw exceptions.
- o método agora tenta identificar o tipo de erro com base na mensagem da exceção capturada.
-  Com base na análise da mensagem de erro, o método pode lançar novas exceções que sejam mais específicas ao contexto de venderProduto, proporcionando clareza adicional sobre o erro ocorrido.
> chore: atualizando método venderProduto

- classes/revendedor.dart
- main.dart
- Criar método verResumo que utiliza as funções criadas anteriormente e realiza um print do resumo de total vendido, média aritmética e lucro obtido.
- Criação do Método verResumo na classe Revendedor;
- Teste de impressão com recebimento dos parâmetros na classe main do repositório local;
- Utilização da função fixarDuasCasasDecimais na impressão dos valores;
> feat: criar método verResumo na classe Revendedor

- classes/brinde.dart
- main.dart
○ consultarPontosNecessarios (retorno: void):
- O método deve realizar um print de uma frase dizendo quantos pontos são necessários para conseguir aquele brinde.   - --- 
- Exemplo: “Para ganhar um(a) Colônia Egeo 10ml você precisa de 15 pontos.”.
- Criado o método consultar pontos necessários;
- Foi chamado o método na main.
> feat: Criar método consultar pontos necessários na classe Brinde

- classes/cliente.dart
- Retornar o método de ordenarProdutosComprados que foi removido durante a mesclagem das branchs anteriores.
- Retorna o método de ordenarProdutosComprados que foi removido durante a mesclagem das branchs anteriores.
> fix: Corrigir método ordenarProdutosComprados

- classes/cliente.dart
- main.dart
verBrindes (retorno: void):
- Método responsável realizar um print dos brindes recebidos em ordem alfabética.
- Exemplo:
> “Brindes recebidos por Maria: Colônia Egeo 10ml Aromatizador de ambientes
- Criado o método ver brindes.
- Foi chamado o método na main.
> feat: Criar método ver brindes na classe cliente

- classes/enums.dart
- Criar enum `Humor` contendo emoções e humores possíveis dentro do `enums.dart`.
- Criar enum de Humor contendo 4 emoções e humores possíveis dentro do `enums.dart`.
> feat: enum contendo emoções

- classes/pessoa.dart
- main.dart
- Criar método ´termometroDoHumor()´ para representar o humor da pessoa receber um parâmetro do tipo Humor, que será um dos humores escritos no enum Humor.
- Criar método ´termometroDoHumor()´ que imprime uma mensagem motivacional de acordo com o humor da pessoa. Foram definidos 4 tipos de humor, todos adequados a todos os tipos de gênero.
> feat: método termômetro do humor

- classes/brinde.dart
- classes/cliente.dart
- classes/enums.dart
- classes/pessoa.dart
- classes/revendedor.dart
- main.dart
- Criar o método `calcularMediaProdutosVendidos()` para calcular e retornar a média aritmética em reais dos produtos vendidos por aquele revendedor utilizando os dados que estiverem dentro da array produtosVendidos.
- Criei o método `calcularMediaProdutosVendidos()` na classe Revendedor.
- Chamada para o método na main.
> feat: método para calcular média de valor dos produtos vendidos

- classes/revendedor.dart
- main.dart
- Criar o método `calcularLucro`  com retorno: double que será responsável por calcular e retornar o lucro em reais obtido por aquele revendedor utilizando o dado de porcentagem de lucro daquele vendedor.
- Criei o método calcularLucro na classe Revendedor.
- Chamada para o método na main.
> feat: método para calcular o lucro do revendedor

- classes/cliente.dart
- main.dart
- Criar método ´verProdutosComprados()´ responsável realizar um print dos produtos comprados em ordem alfabética, juntamente com os seus valores e sem retorno.
- Criei o método ´verProdutosComprados()´ responsável realizar um print dos produtos comprados em ordem alfabética, juntamente com os seus valores e sem retorno onde primeiro verifico se tem produtos comprados, depois prossigo com a validação de ordem alfabetica dos nomes dos produtos e imprimo na tela os itens comprados.
> feat: método produtos comprados

- classes/produto.dart
- main.dart
- atualizar método realizarVenda para adicionar throw exceptions
- Adicionei um parâmetro opcional quantidade com valor padrão de 1 ao método realizarVenda. Isso permite realizar vendas de múltiplas unidades de um produto em uma única.
- Incluí uma verificação para garantir que a quantidade vendida seja sempre um número positivo. Tentar vender uma quantidade negativa ou zero agora resulta em uma exceção, aumentando a robustez do código.
- Após cada venda, o sistema verifica se o estoque do produto está baixo (definido aqui como 3 unidades ou menos) e notifica o usuário.
> chore: atualizando método realizarVendar

- classes/cliente.dart
- Ajustar o método `comprarProduto (retorno: void) `na classe Cliente. O método continuará realizando a compra do produto, porém no sucesso da compra, deve-se adicionar +1 ponto no atributo pontos daquele cliente.
- Foi ajustado o método de modo que, ao finalizar uma compra com sucesso,  o atributo chamado `pontos`  foi incrementado.
> refactor: ajuste do método comprar produto na classe cliente 

- classes/cliente.dart
- main.dart
- Criar método trocarPontosPorBrinde responsável por realizar uma troca de pontos por brinde.
- Criei o método de acordo com a tarefa designada no trello.
> feat: método que troca os pontos por brindes

- classes/brinde.dart
- ○ qtdEmEstoque (tipo: int):
Representa a quantidade do produto em estoque (exemplo: 5).
Atributo obrigatório, cujo valor inicial deve ser recebido no construtor da classe.
- Adicionado o atributo "qntEmEstoque" e a chamada dentro do construtor "Brinde({required this.qtdEmEstoque});" dentro da Classe Brinde.
> feat: Criado o atributo de quantidade em estoque na Classe Brinde

- classes/cliente.dart
- main.dart
- Desafio 3
- Criar novo método `consultarTotalPontos (retorno: void)` na classe Cliente. Método responsável por mostrar o total de pontos que aquele cliente possui. Exemplo: “Maria possui 7 pontos”.
- Foi criado o método `consultarTotalPontos (retorno: void)`  em cliente.dart
- Além do que foi pedido, foi verificado se deveria ser usado na mensagem plural ou singular dependendo da quantidade de pontos
- O teste/chamada para o método foi feito na main
> feat:  adiciona o metodo consultar total pontos

- classes/brinde.dart
- main.dart
- Criação de método de ordenação de brindes.
- Criação de método estático, o que significa que ele pertence à classe Brinde e não a uma instância específica de Brinde. Ele recebe uma lista de Brinde como argumento.
- A lista de brindes é ordenada usando o método sort da lista
-  O critério de comparação é o nome do brinde, que é acessado através do atributo nome de cada Brinde.
- A função compareTo do tipo String é usada para determinar a ordem alfabética dos nomes.
- Após a ordenação, o método imprime os brindes em ordem alfabética junto com seus pontos necessários para adquiri-los. Isso é útil para verificar se a lista foi ordenada corretamente.
> Feature: Criação método ordernaBrindes

- classes/brinde.dart
- classes/cliente.dart
- main.dart
- Criar método `realizarTroca` (retorno: void). O método deve verificar se ainda há aquele produto em estoque. Caso haja, deve-se:
- Diminuir em 1 a quantidade no estoque;
- Realizar um print dizendo que a troca foi realizada e que a pessoa ganhou aquele brinde.
- Caso não tenha em estoque lançar uma exceção dizendo que não temos o produto em
estoque.
- Criei o método `realizarTroca()`para verificar se tem o brinde em estoque ou não e imprimir na tela a mensagem de validação.
> feat: método realizar troca na classe brinde

- classes/cliente.dart
Criar atributo pontos (tipo: int) que deve ser inicializado dentro da classe com o valor 0 (zero). Não deve ser recebido no construtor.
- Adicionei o atributo `pontos` inicializado dentro da classe com o valor 0.
> feat: criar atributo pontos na classe cliente

- classes/brinde.dart
Criar atributo brindes (tipo: Array de Brindes):
- Atributo que deve ser inicializado com uma array vazia dentro da classe. Não deve ser recebido no construtor.
- Adicionei o atributo `brindes` como uma lista vazia dentro da classe `Cliente`.
> feat: criar atributo brindes

- classes/enums.dart
- classes/pessoa.dart
- main.dart
- Criar termômetro do humor e enums com humor.
- Criar termômetro do humor e enums com humor.
> feat: termometro e enums contendo humor

- classes/brinde.dart
- classes/cliente.dart
- main.dart
- Refatorar a classe Cliente, testando e corrigindo possíveis problemas.
- Organizei os atributos da classe e métodos de acordo com o que ficou acordado pelo time;
- Corrigir os bugs de teste e métodos;
- O método ordenarBrindes() foi adicionado para a classe.
> Refactor: Refatoração da Classe Cliente

- classes/produto.dart
Refatoração da classe produto.
-  Mantive o padrão de nomenclatura dos métodos e variáveis, 
- Adicionei chaves em torno dos blocos de código dos métodos realizarVenda e verReceitaGerada para garantir clareza
- Adicionei espaçamento vertical entre os métodos e seções de código para melhorar a legibilidade do código.
- Removi comentários redundantes que apenas repetiam o que já estava claro no código.
> Feact: Refactor Produto

- main.dart
Refatoração da main.
Refatoração da main e chamada do menu de iteração.
> feat: Refatoração da main.

- readme.md
- Atualizar o README do projeto
- Foi criado um template para o time para mantermos um padrão, pensando tanto em documentação quanto visual
- Foram adicionados pontos como: 
-  Tabela de conteúdo
-  Objetivo do projeto
- Estrutura do projeto
- Features
- Instalação
- Links
- Squad
**Antes**:
**Depois**:
> docs: atualiza o readme do projeto
